export const dev = {
  appName: 'Friendly Application Label',
  appVersion: '1.0.3',
  builtForMacStore: false,
  builtForWinStore: false,
  chromeVersion: '56.0.2924.87',
  electronVersion: '1.6.10',
  envPlatform: 'linux',
  envProcessorArch: 'x64',
  executingInDevPath: true,
  pathToAppCfg: '/usr/local/userData',
  pathToAppData: '/usr/local/appData',
  pathToAppDir: '/usr/applications',
  pathToDocDir: '/usr/local/documents',
  pathToDwnDir: '/usr/local/downloads',
  pathToResources: 'usr/resources',
  pathToTempDir: 'usr/temp',
  pathToUsrHome: '/usr',
  updateFeedUrl: 'www.criticide.com/some/path/to/feed/url',
  userLocale: 'en',
};

export const prod = {
  appName: 'Friendly Application Label',
  appVersion: '1.0.3',
  builtForMacStore: false,
  builtForWinStore: false,
  chromeVersion: '56.0.2924.87',
  electronVersion: '1.6.10',
  envPlatform: 'linux',
  envProcessorArch: 'x64',
  executingInDevPath: false,
  pathToAppCfg: '/usr/local/userData',
  pathToAppData: '/usr/local/appData',
  pathToAppDir: '/usr/applications',
  pathToDocDir: '/usr/local/documents',
  pathToDwnDir: '/usr/local/downloads',
  pathToResources: 'usr/resources',
  pathToTempDir: 'usr/temp',
  pathToUsrHome: '/usr',
  updateFeedUrl: 'www.criticide.com/some/path/to/feed/url',
  userLocale: 'en',
};
